import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';
import 'package:unimatcher/utils/constants/sizes.dart';

class UMDropDown extends StatelessWidget {
  const UMDropDown({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
        (UMSizes.defaultSpace * 0.6),
        (UMSizes.defaultSpace * 0.1),
        (UMSizes.defaultSpace * 0.6),
        (UMSizes.defaultSpace * 0.6),
      ),
      child: DropdownButtonFormField(
        isExpanded: true,
        decoration: const InputDecoration(
          prefixIcon: Icon(
            Iconsax.sort,
          ),
          hintText: 'Select a University',
        ),
        onChanged: (value) {},
        items: [
          'University of the Punjab',
          'Aga Khan University',
          'Quaid-i-Azam University',
          'Lahore University of Management Sciences',
          'University of Karachi',
          'Bahauddin Zakariya University',
          'University of Engineering and Technology, Lahore',
          'COMSATS Institute of Information Technology',
          'University of Agriculture, Faisalabad',
          'National University of Sciences and Technology',
          'International Islamic University, Islamabad',
          'University of Peshawar',
          'National University of Computer and Emerging Sciences',
          'Bahria University',
          'Islamia University of Bahawalpur',
          'University of Sindh',
          'DOW University of Health Sciences',
          'University of Lahore',
          'Mehran University of Engineering and Technology',
          'Government College University, Lahore',
          'NED University of Engineering and Technology',
          'Abdul Wali Khan University Mardan',
          'University of Education - Pakistan',
          'University of Central Punjab',
          'University of Sargodha',
          'Institute of Business Administration',
          'Fatima Jinnah Women University',
          'Forman Christian College',
          'Government College University, Faisalabad',
          'Ghulam Ishaq Khan Institute of Engineering Sciences and Technology',
          'University of Engineering and Technology, Peshawar',
          'University of Engineering and Technology, Taxila',
          'Pir Mehr Ali Shah Arid Agriculture University',
          'Riphah International University',
          'Lahore College for Women University',
          'University of Balochistan',
          'King Edward Medical University',
          'Pakistan Institute of Engineering and Applied Sciences',
          'Gomal University',
          'Liaquat University of Medical and Health Sciences',
          'University of Gujrat',
          'National University of Modern Languages',
          'University of Health Sciences, Lahore',
          'University of Veterinary and Animal Sciences',
          'Information Technology University',
          'Khyber Medical University',
          'Federal Urdu University of Arts, Sciences and Technology',
          'National Defence University',
          'Hazara University',
          'Air University',
          'Pakistan Institute of Development Economics',
          'National Textile University',
          'Jinnah Sindh Medical University',
          'Institute of Space Technology',
          'Sukkur Institute of Business Administration',
          'Iqra University',
          'Kinnaird College for Women',
          'Islamia College Peshawar',
          'Lahore School of Economics',
          'Hamdard University',
          'Ziauddin University',
          'Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology',
          'Kohat University of Science and Technology',
          'Sindh Agriculture University',
          'University of Agriculture, Peshawar',
          'University of Malakand',
          'University of Azad Jammu and Kashmir',
          'Balochistan University of Information Technology, Engineering and Management Sciences',
          'University of Haripur',
          'Rawalpindi Medical University',
          'Karakurum International University',
          'Foundation University Islamabad',
          'Fatima Jinnah Medical University',
          'University of Management and Technology - Lahore',
          'HITEC University',
          'Karachi Institute of Economics and Technology',
          'Beaconhouse National University',
          'Isra University',
          'Sarhad University of Science and Information Technology',
          'Shah Abdul Latif University',
          'Quaid-e-Awam University of Engineering, Science and Technology',
          'Mohammad Ali Jinnah University',
          'University of Science and Technology, Bannu',
          'Baqai Medical University',
          'Sir Syed University of Engineering and Technology',
          'University of Swat',
          'Mirpur University of Science and Technology',
          'Sindh Madresatul Islam University',
          'National College of Business Administration and Economics',
          'Dawood University of Engineering and Technology',
          'Jinnah University for Women',
          'Bacha Khan University',
          'University of Wah',
          'Shaheed Benazir Bhutto Women University',
          'Preston University',
          'Abasyn University',
          'Indus University, Pakistan',
          'Government College Women University, Faisalabad',
          'Government Sadiq College Women University, Bahawalpur',
          'Shaheed Benazir Bhutto University, Shaheed Benazirabad',
        ]
            .map((option) => DropdownMenuItem(
                  value: option,
                  child: Text(
                    option,
                    style: const TextStyle(
                      fontSize: 12,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ))
            .toList(),
      ),
    );
  }
}
